"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import AuthProviderPro from "@/Components/AuthProviderFiles/AuthProviderPro";
import Provider from "@/Components/Provider/Provider";
import { QueryClient, QueryClientProvider } from "react-query";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Free Flow",
  description: "Generated by Team Mern Militia",
};

const queryClient = new QueryClient();

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <QueryClientProvider client={queryClient}>
        <Provider>
          <body className={inter.className}>
            <AuthProviderPro>
              <div className="outlineSpace select-none">{children}</div>
            </AuthProviderPro>
          </body>
        </Provider>
      </QueryClientProvider>
    </html>
  );
}
